### ISSUE TITLE
Where is the release?

### ISSUE THREAD

**Issue by ghost** [gdbinit/MachOPlugin#1]

**Comment by ghost** [comment]
@gdbinit I don't want to download 10 gigabytes of porn from Microsoft build toolchain just to compile one (or three) simple plugins.

**Comment by ghost** [comment]
@gdbinit publish binaries please.

**Comment by ghost** [comment]
It's a bad habit not publishing binaries and forcing everyone to build this

**Comment by gdbinit** [comment]
It's your fucking problem so stop spamming this.
